Ajout des operations dans un fichier (serveur)
matthieu637/cpp-2a-info pull request #12
Opened 2017-02-24 15:32 UTC by david540

Pour l'instant j'ai écris dans un fichier avec un saut de ligne entre chaque opération :
J'ai un doute: le "\r\n" pour le saut de ligne fonctionne pour tous les systèmes d'exploitations ?
['Achat','David','Google',5.0,5]
['Achat','David','Trydea',5.0,5]
['Vente','David','Trydea',2.0,5]
['AnnulationAchat','David','Google',5.0,5]
Et je garde que la sauvegarde de la dernière partie jouée.
J'ai fais ça mais je ne sais pas ce qui est attendu pour la mise en forme, etc...

2017-02-24 16:02 UTC, matthieu637 requested changes
Modificatifs minimes.

2017-02-24 16:02 UTC, matthieu637 commented on 2017/SimBourse/src/core/Marche.java
> +		}catch (FileNotFoundException e) {
Vu que tu ne fais pas de traitement particulier des exceptions tu peux changer FileNotFoundException par Exception.
Ça permettra de supprimer le second catch.

2017-02-24 16:02 UTC, matthieu637 commented on 2017/SimBourse/src/core/Marche.java
> +			Writer writer = new OutputStreamWriter(new FileOutputStream(new File("OperationsDernierePartie.txt")), charset);
Ça serait bien de définir le nom du fichier (qui contient son chemin) dans core.Config pour tout regrouper. 
Je pourrai rendre le fichier publique plus facilement.

2017-02-24 16:02 UTC, matthieu637 commented on 2017/SimBourse/src/core/Marche.java
>  	public void destroy(){
Tu peux ajouter le mot clé synchronised dans la déclaration de la méthode pour éviter l'écriture concurrente du fichier. Si plusieurs parties ont lieu en même temps.

2017-02-24 16:02 UTC, matthieu637 commented on 2017/SimBourse/src/core/Marche.java
> +			for (Operation operation : liste_Operations){
A nouveau pas besoin de for : String.valueOf(liste_Operations) suffit.
Le saut de ligne servira à différencier chaque partie.

2017-02-24 16:02 UTC, matthieu637 commented on 2017/SimBourse/src/core/Marche.java
> +				writer.write("\r\n");
Habituellement j'utilise uniquement "\n" mais je suis sous Linux.

2017-02-24 16:03 UTC, matthieu637 commented
Dernière info : il faut ajouter les données à la fin du fichier s'il existe.
Pour la mise en forme le String.valueOf suffira (avec saut de ligne entre chaque partie).

2017-02-24 16:54 UTC, david540 commented
Voilà j'ai fais les modifs il faudra aussi changer le chemin dans Config.java, il faut juste vérifier que le \r\n fait un retour à la ligne aussi sur linux (le \n ne marche pas sur windows...)

2017-02-24 22:41 UTC, matthieu637 approved these changes

2017-02-24 22:41 UTC, merged

2017-02-24 22:41 UTC, matthieu637 commented
Merci.

2017-02-25 10:47 UTC, matthieu637 commented
Fichier disponible ici en temps réel : https://matthieu-zimmer.net/%7Ematthieu/courses/simbourse.log