Ajout limite taille liste_ventes et liste_achats envoyé par le serveur
matthieu637/cpp-2a-info pull request #14
Opened 2017-02-25 20:40 UTC by david540

C'est le code que j'ai, celui avec lequel j'ai les issues que j'ai envoyé (je les avais aussi avant modifications)

2017-02-25 23:52 UTC, matthieu637 commented
J'ai essayé de corriger les exceptions que tu as trouvé (9d82199e3f4eca2121c2475aa1381964ffca5c2a), il faut donc que tu adaptes un peu ton code.

2017-02-25 23:54 UTC, matthieu637 commented
Sinon sur le code proposé, tu peux juste définir la valeur par défaut de nbMaxElemListe à 0 :
nbMaxElemListe=0
dans la déclaration de la fonction client.py.

2017-02-26 01:09 UTC, david540 commented
Oui ça marche ! Je vais mettre mes modifs dans mon pull request.

2017-02-26 01:53 UTC, david540 commented
Voilà c'est fait. 
Par contre pour avoir une sous liste des listesAchats et listesVentes j'ai fais un cast avec une linkedList mais il y a peut être moins couteux maintenant.

2017-02-26 09:19 UTC, matthieu637 requested changes
Quelques détails mineurs à améliorer.

2017-02-26 09:19 UTC, matthieu637 commented on 2017/SimBourse/src/core/Marche.java
> +		if(nbMaxAchats<=0 || nbMaxAchats>liste_achats.get(a).size())
tu peux transformer le > strict en >= ici.

2017-02-26 09:19 UTC, matthieu637 commented on 2017/SimBourse/src/core/Marche.java
> +			r=String.valueOf(new LinkedList<Ordre>(liste_achats.get(a)).subList(0, nbMaxAchats));
En effet l'opération de création de liste à partir du set coûte n opérations, puis à nouveau nbMaxAchats opérations. Tu peux adopter la solution que tu avais proposé pour limiter la taille de l'historique qui coûtera moins cher. Le mieux serait même de regrouper le tout dans une fonction et faire les 3 appels (ventes, achats, historique) si c'est possible (attention à bien garder l'ordre cependant). 
```
private String SetVersString(Set set, int taille)
```

2017-02-26 09:19 UTC, matthieu637 commented on 2017/SimBourse/src/network/Client.java
> -				} else if (userInput.startsWith(ACHATS) && arguments.length == 2 && StringUtils.isNumeric(arguments[1])&& peut_jouer){
Dans l'optique d'optimiser les messages réseaux, tu pourrais garder l'ancien code (ACHATS+ACTION) et ajouter un autre else if indépendant (ACHATS+ACTION+NOMBRE). Comme ça s'il veut récupérer la liste de tous les achats/ventes. Il n’envoie pas le nombre pour rien. Mais bon c'est vraiment du détails.

2017-02-26 09:19 UTC, matthieu637 commented on 2017/client.py
> +		self.__envoyer(self.__message["ACHATS"]+str(numAction)+" "+str(nbMaxElemListe))
Pour faire suite à la remarque précédente, si nbMaxElemListe vaut 0, pas besoin de l'envoyer.

2017-02-26 12:40 UTC, david540 commented
Voilà j'ai refait quelques modifications, maintenant la complexité de la création de la sous liste est en O(nbMaxAchats) je crois.
J'ai fais un seul grand if(userInput.startsWith(ACHATS)) puis j'ai géré les deux cas arguments.length == 2 et arguments.length == 3 ensuite mais du coup j'ai du ajouter pas mal de "else envoyer(out,-4)" donc le code perd en lisibilité, je sais pas ce qui est le mieux
J'ai aussi ajouter des else envoyer(out,-4) là ou il n'y en avait pas (mais bon c'était dans les cas ou les demandes n'étaient pas faites par client.py donc ça ne posait pas de problèmes)

2017-02-26 12:47 UTC, matthieu637 approved these changes

2017-02-26 12:47 UTC, matthieu637 commented
C'est bien comme ça, merci. 
A terme, le code devrait être séparé dans différentes classes pour chaque requête, mais ce n'est pas très important.

2017-02-26 12:47 UTC, merged