Ajout modes banques et mode examen
matthieu637/cpp-2a-info pull request #23
Opened 2017-03-19 11:42 UTC by david540

Dans client.py: si le parametre modeBanque vaut 1 : presence ou non de banque, 2: presence de banque, 3: pas de banque
modeExamen: 1 si une seule connexion par utilisateur est accepté(mode Examen)
0 sinon

2017-03-19 19:25 UTC, matthieu637 requested changes
Super merci. Il y a quelques modifs à revoir.

D'ailleurs, penses à mettre à jour libererPartie dans Client (en retirant l'identifiant dans ta listeHostAdress). Au cas où quelqu'un rejoint, bug et voudrait rejoindre à nouveau avant le top.

2017-03-19 19:25 UTC, matthieu637 commented on 2017/SimBourse/src/network/Client.java
> +					if ((modeBanque.equals("1")||modeBanque.equals("2")||modeBanque.equals("3")) && (modeExam.equals("0")||modeExam.equals("1"))){
C'est un détail, mais pourquoi il y en a un qui commence à 0 et l'autre à 1?

2017-03-19 19:25 UTC, matthieu637 commented on 2017/SimBourse/src/network/Client.java
> +					if (current.isModeExamen()&&current.testUniciteDeLaConnexion(client)==false)
"== false", est équivalent à "!"

2017-03-19 19:25 UTC, matthieu637 commented on 2017/SimBourse/src/network/Partie.java
> +	private final int modeExam;
changer le modeExam par un booléen serait plus lisible

2017-03-19 19:25 UTC, matthieu637 commented on 2017/SimBourse/src/network/Partie.java
> +	public Boolean isModeExamen(){
A moins d'avoir besoin d'un objet (avec son pointeur associé), le type boolean (vs objet Boolean) suffit en général.

2017-03-19 19:25 UTC, matthieu637 commented on 2017/SimBourse/src/network/Partie.java
> +		if(modeExam==1)
Si modeExam est un booléen, il suffit de le retourner. On gagne ainsi une comparaison.

2017-03-19 19:25 UTC, matthieu637 commented on 2017/SimBourse/src/network/Partie.java
> +			liste_HostAdress.add(s.getInetAddress().getHostAddress());
Faire une restriction sur les IP publiques est trop strict. Plusieurs VMs peuvent avoir la même IP publique, pareil au niveau de l'université.
En théorie, il faudrait identifier les étudiants par des clés uniques connues d'eux seuls. (cf todo list)
Pour le moment, je te propose d'utiliser 
```
nom_complet+":"+s.getInetAddress().getHostAddress()
```
pour la clé, même si ça n'est pas vraiment idéal.

2017-03-19 19:25 UTC, matthieu637 commented on 2017/SimBourse/src/network/Partie.java
> +	public Boolean testUniciteDeLaConnexion(Socket s){
Il faudra ajouter "nom_complet"

2017-03-19 22:44 UTC, david540 commented
Je crois avoir fait les modifications. 
J'ai mis 0 ou 1 pour modeExam pour refléter un boolean et 1, 2 ou 3 pour refléter un choix mais bon je ne sais pas si c'est plus clair pour l'utilisation côté client ou pas.

2017-03-20 09:13 UTC, matthieu637 requested changes
Il manque encore les opérations de suppression dans la liste liste_HostAdress. 
Cf mon commentaire précédent : 
"D'ailleurs, penses à mettre à jour network.Client::libererPartie dans network.Client (en retirant l'identifiant dans ta listeHostAdress). Au cas où quelqu'un rejoint, bug et voudrait rejoindre à nouveau avant le top."

2017-03-20 09:13 UTC, matthieu637 commented on 2017/SimBourse/src/network/Partie.java
> +			isModeExam=false;
ces 4 lignes peuvent être réduite en 1 seule :
```
modeExamen = isModeExam == 1;
```

2017-03-20 12:44 UTC, david540 commented
Voilà je crois que c'est bon

2017-03-20 12:47 UTC, matthieu637 commented
Oui merci.

2017-03-20 12:48 UTC, merged